"""restructure back

Revision ID: 10d6e3910967
Revises: e89db9af5bae
Create Date: 2018-10-14 00:07:23.067940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10d6e3910967'
down_revision = 'e89db9af5bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_expert')
    op.add_column('user_service', sa.Column('is_expert', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_service', 'is_expert')
    op.add_column('services', sa.Column('is_expert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
