"""DUMMY DATA

Revision ID: 168b9b816bfd
Revises: b8111244756b
Create Date: 2018-10-14 04:00:16.331782

"""
import random

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, Boolean
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '168b9b816bfd'
down_revision = 'b8111244756b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('user_service', 'is_expert',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('users', 'is_guide',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # Service
    my_other_table = table('user_service',
                           column('user_id', Integer),
                           column('service_id', Integer),
                           column('is_expert', Boolean)
                           )
    user_service_list = []
    for x in range(48):
        user_service_list.append({
            'user_id': int(x + 1),
            'service_id': (x % 8) + 1,
            'is_expert': random.choice([True, False])
        })

    op.bulk_insert(my_other_table,
                   user_service_list
                   )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_guide',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('user_service', 'is_expert',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('conversations', 'is_read',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
