"""A bunch of shit. Not sure what exactly

Revision ID: 1cf7bf10c6f2
Revises: d7ba7714322d
Create Date: 2018-10-13 18:41:28.868509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cf7bf10c6f2'
down_revision = 'd7ba7714322d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', mysql.INTEGER(display_width=11, unsigned=True), nullable=True))
    op.drop_constraint('fk_review_event_id', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_review_service_id', 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_review_user_id', 'reviews', 'users', ['user_id'], ['id'])
    op.drop_column('reviews', 'service_id')
    op.drop_column('reviews', 'event_id')
    op.alter_column('users', 'is_guide',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_guide',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.add_column('reviews', sa.Column('event_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('service_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True))
    op.drop_constraint('fk_review_user_id', 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_review_service_id', 'reviews', 'services', ['service_id'], ['id'])
    op.create_foreign_key('fk_review_event_id', 'reviews', 'events', ['event_id'], ['id'])
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
