"""Modify_User_model

Revision ID: 4919132f1dfe
Revises: ca87ac02f845
Create Date: 2018-10-13 11:35:40.635419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4919132f1dfe'
down_revision = 'ca87ac02f845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('birthday', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('language_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('latitude', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('longitude', mysql.FLOAT(), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'language_id')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
