"""Add is expert to service user table

Revision ID: 737c17093c61
Revises: dee45aced50b
Create Date: 2018-10-13 23:58:55.388230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '737c17093c61'
down_revision = 'dee45aced50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_service', sa.Column('is_expert', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_service', 'is_expert')
    # ### end Alembic commands ###
