"""Generate dummy data in user table

Revision ID: 74872ad99951
Revises: ba4f9480ba23
Create Date: 2018-10-13 12:26:39.098958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74872ad99951'
down_revision = 'ba4f9480ba23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
