"""Adds is_guide field to user model

Revision ID: 8406d2423de7
Revises: 74872ad99951
Create Date: 2018-10-13 13:37:11.377125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8406d2423de7'
down_revision = '74872ad99951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_guide', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_guide')
    # ### end Alembic commands ###
