"""Generate services dummy data

Revision ID: 9ddc02a10adf
Revises: 369cd365eefd
Create Date: 2018-10-13 22:29:34.943215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date, Float, Boolean

# revision identifiers, used by Alembic.
revision = '9ddc02a10adf'
down_revision = '369cd365eefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    my_table = table('services',
        column('name', String),
        column('category', String)
    )

    op.bulk_insert(my_table,
    [
        {'category': 'General', 'name':'Get a driver\'s license'},
        {'category': 'General', 'name':'Register my vehicle'},
        {'category': 'General', 'name':'Navigate public transportation'},
        {'category': 'General', 'name':'Share local restaurants'},
        {'category': 'Money', 'name':'Open a bank account'},
        {'category': 'Money', 'name':'Open a credit card'},
        {'category': 'Money', 'name':'Understand my medical bill'},
        {'category': 'Money', 'name':'Understand my electricity bill'},
        {'category': 'Information Technology Professionals', 'name':'Resume assistance'},
        {'category': 'Information Technology Professionals', 'name':'Networking'},
        {'category': 'Information Technology Professionals', 'name':'Skill transferability'},
        {'category': 'Medical Professionals', 'name':'Resume assistance'},
        {'category': 'Medical Professionals', 'name':'Networking'},
        {'category': 'Medical Professionals', 'name':'Skill transferability'},
        {'category': 'Entrepreneurship', 'name':'Legal Assistance'},
        {'category': 'Entrepreneurship', 'name':'Marketing'}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
