"""Conversation and ConversationContent

Revision ID: b62469de75d8
Revises: 1cf7bf10c6f2
Create Date: 2018-10-13 18:44:43.335959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b62469de75d8'
down_revision = '1cf7bf10c6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id_one', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.Column('user_id_two', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id_one'], ['users.id'], name='fk_conversation_user_id_one'),
    sa.ForeignKeyConstraint(['user_id_two'], ['users.id'], name='fk_conversation_user_id_two'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('conversation_contents',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11, unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name='fk_conversation_content_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.alter_column('users', 'is_guide',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_guide',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_table('conversation_contents')
    op.drop_table('conversations')
    # ### end Alembic commands ###
