"""DUMMY DATAAAAAAA

Revision ID: b9e5b67d37d1
Revises: 168b9b816bfd
Create Date: 2018-10-14 04:38:11.020813

"""
import random

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, Boolean, String
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9e5b67d37d1'
down_revision = '168b9b816bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('user_service', 'is_expert',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('users', 'is_guide',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # Service
    my_other_table = table('reviews',
                           column('user_id', Integer),
                           column('text', String),
                           column('rate', Integer)
                           )
    reviews_list = []
    good_things_people_say = [
        'Great experience!',
        'Good person',
        'So helpful!',
        'Wow',
        'Such good service',
        'Very pleasant',
        'Helped me big time',
        'Super friendly',
        'We are actually best friend now!',
        'Saved my life!',
        ':)',
        'Thank you!'
    ]
    for _ in range(100):
        reviews_list.append({
            'user_id': (int)((random.random() * 100) % 48) + 1,
            'text': random.choice(good_things_people_say),
            'rate': random.choice([3, 4, 5])
        })

    op.bulk_insert(my_other_table,
                   reviews_list
                   )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_guide',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('user_service', 'is_expert',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('conversations', 'is_read',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
