"""change_language_to_string

Revision ID: ba4f9480ba23
Revises: 4919132f1dfe
Create Date: 2018-10-13 11:46:42.846317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4f9480ba23'
down_revision = '4919132f1dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'language_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False))
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
