"""restructure conversation

Revision ID: dee45aced50b
Revises: 9ddc02a10adf
Create Date: 2018-10-13 22:44:31.304651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dee45aced50b'
down_revision = '9ddc02a10adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_contents')
    op.add_column('conversations', sa.Column('content', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('conversations', sa.Column('is_read', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
