"""restructure

Revision ID: e89db9af5bae
Revises: 737c17093c61
Create Date: 2018-10-14 00:04:55.372289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e89db9af5bae'
down_revision = '737c17093c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_expert', sa.BOOLEAN(), nullable=False))
    op.drop_column('user_service', 'is_expert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_service', sa.Column('is_expert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('services', 'is_expert')
    # ### end Alembic commands ###
