"""Add user_id_two for event

Revision ID: f31e620a4453
Revises: 10d6e3910967
Create Date: 2018-10-14 02:35:28.711315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f31e620a4453'
down_revision = '10d6e3910967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_index('fk_user_event_id1', table_name='user_event')
    op.create_foreign_key('fk_user_event_id4', 'user_event', 'users', ['user_id_one'], ['id'])
    op.create_foreign_key('fk_user_event_id3', 'user_event', 'users', ['user_id_two'], ['id'])
    op.drop_column('user_event', 'user_id')
    op.alter_column('user_service', 'is_expert',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('users', 'is_guide',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_guide',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('user_service', 'is_expert',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.add_column('user_event', sa.Column('user_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True))
    op.drop_constraint('fk_user_event_id3', 'user_event', type_='foreignkey')
    op.drop_constraint('fk_user_event_id4', 'user_event', type_='foreignkey')
    op.create_index('fk_user_event_id1', 'user_event', ['user_id'], unique=False)
    op.alter_column('conversations', 'is_read',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
